export const VIEW_FESTIVE = 'VIEW_FESTIVE'
export const REMOVE_FESTIVE = 'REMOVE_FESTIVE'
export const SELECT_FESTIVE = 'SELECT_FESTIVE'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'